env:
  browser: true
  es2020: true
extends:
  - 'airbnb-base'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react-hooks/recommended'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  import/extensions: 0
  no-console: 0
  no-unused-expressions: 0